### ISSUE TITLE
[ReleaseTools] additional scenario 

### ISSUE THREAD

**Issue by jeonghanlee** [icshwi/e3-tools#1]
In case, when three golden version numbers are exactly same with a master and module version branch, but files are changed. what kind of procedure to *update* the module version branch files from the changes in the master branch?

**Comment by jeonghanlee** [comment]
* master branch can be handled properly
* do we need to cover "each branch"?

**Comment by jeonghanlee** [comment]
Yes, we need to develop the additional user case for a version branch.

**Comment by waynelewis** [comment]
The functionality of these tools is in the e3/tools folder in https://gitlab.esss.lu.se/e3/e3
