### ISSUE TITLE
e3 module url full

### ISSUE THREAD

**Issue by rizzoa** [icshwi/e3-tools#11]
Hi
in order to create the SRC repo on gitlab I have to explicitly add .git to the name of the src module path
e.g.
E3_MODULE_SRC_PATH:=myepics7mod.git
otherwise I get the error 

Cloning into 'myepics7mod'...
error: RPC failed; result=22, HTTP code = 404
fatal: The remote end hung up unexpectedly

Please fix, otherwise when you want a local src repo, it will create e.g. 
myepics7mod.git-loc

maybe replacing the line 294 of e3TemplateGenerator
_E3_MODULE_GITURL_FULL=${epics_mod_url}/${_E3_MODULE_SRC_PATH}

to 

_E3_MODULE_GITURL_FULL=${epics_mod_url}/${_E3_MODULE_SRC_PATH}.git

will fix

**Comment by jeonghanlee** [comment]
This issue will be handled within the early one as https://github.com/icshwi/e3-tools/issues/6

**Comment by jeonghanlee** [comment]
@rizzoa  I updated the repo, please check that feature, and let me know if there are more bugs.
