### ISSUE TITLE
Missing ".git" from _E3_MODULE_GITURL_FULL in e3TemplateGenerator.bash

### ISSUE THREAD

**Issue by jsparger** [icshwi/e3-tools#6]
In `e3TemplateGenerator.bash`, the variable `E3_MODULE_GITURL_FULL` is missing ".git" from the end. It is created with this line:
```
_E3_MODULE_GITURL_FULL=${epics_mod_url}/${_E3_MODULE_SRC_PATH}
```
You can compare this to `_E3_TGT_URL_FULL`, which is created like this (and does contain ".git")
```
_E3_TGT_URL_FULL=${e3_target_url}/${_E3_MOD_NAME}.git
```
Without adding ".git" to the end of _E3_MODULE_GITURL_FULL, a git clone from a source other that Github will fail. Github does not care if ".git" is present, but some other sources do. Since Github accepts it, this probably didn't come up before during testing.

Could you please add this small fix? Thanks

**Comment by nicklasholmberg2** [comment]
This is still an issue, it took me a couple of hours to identify it.

**Comment by jeonghanlee** [comment]
It is the known issue on only gitlab. I will catch up slowly.  BTW, you are welcome to do "pull request" if you can. :)

**Comment by jeonghanlee** [comment]
@nicklasholmberg and @jsparger , please check the latest commit to verify whether it works with gitlab or not.  I am not using the internal gitlab so I cannot verify it work or not with gitlab. The current implementation works with github.

**Comment by jeonghanlee** [comment]
Due to no response, I close it. If one has more, please create new one.
