### ISSUE TITLE
duplicated functions in .e3_template_funcs.cfg

### ISSUE THREAD

**Issue by rizzoa** [icshwi/e3-tools#9]
Hi Han,
In the .e3_template_funcs.cfg file the following functions
- _add_configure_siteApps_
- _add_configure_siteApps_local_
have a duplicated (maybe _add_configure_siteApps_local_ are even different) which create the following error when I try to create a template:

._e3_template_funcs.cfg: line 1495: add_CONFIG_SITE_SYSTEMAPPS: command not found
./e3TemplateGenerator.bash: line 403: add_configure_module: command not found_

Could you please check and fix?
Thanks

**Comment by jeonghanlee** [comment]
restructured and add some tests in travis. implemented at 8822467
